# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryfunc', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=1000),
        ),
    ]
