# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmanager', '0002_auto_20190310_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='皇后大道', max_length=128),
        ),
    ]
