# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmanager', '0004_auto_20190312_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('book', models.ManyToManyField(to='booksmanager.Book')),
            ],
        ),
    ]
